"""Assemble a recruiter-facing markdown summary from all model outputs."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from .config import REPORTS_DIR
from .utils import fmt_money, fmt_pct


def _df_to_md(df: pd.DataFrame, floatfmt: int = 4) -> str:
    return df.round(floatfmt).to_markdown(index=False)


def build_summary(results: dict) -> Path:
    pd_res = results["pd"]
    lgd_res = results["lgd"]
    ecl_res = results["ecl"]
    stress_res = results["stress"]
    ews_res = results["ews"]

    best = pd_res.best_model_name
    pdm = pd_res.metrics
    port = ecl_res.portfolio

    lines: list[str] = []
    a = lines.append

    a("# Credit Risk Analytics — Model Summary\n")
    a("> **Synthetic data disclaimer.** All figures below are produced from a "
      "synthetic, reproducible portfolio generated for demonstration. They are "
      "*not* derived from real lending data and must not be used for production "
      "underwriting.\n")

    a("## Portfolio at a glance\n")
    a(f"- Loans modelled: **{pdm['n_train'] + pdm['n_test']:,}**")
    a(f"- Total exposure at default (EAD): **{fmt_money(port['total_ead'])}**")
    a(f"- Probability-weighted ECL: **{fmt_money(port['weighted_ecl'])}** "
      f"({fmt_pct(port['coverage_ratio'])} coverage ratio)")
    a(f"- IFRS 9 staging: Stage 1 **{port['n_stage1']:,}** / "
      f"Stage 2 **{port['n_stage2']:,}** / Stage 3 **{port['n_stage3']:,}**\n")

    # --- Model 1: PD ---
    a("## 1. Probability of Default (PD)\n")
    a(f"Best model by ROC-AUC: **{best}**. Metrics on a held-out 30% test set:\n")
    perf = pd.DataFrame(
        [{"model": m, **{k: pdm[m][k] for k in ("roc_auc", "pr_auc", "brier")}}
         for m in ("logistic_regression", "gradient_boosting")]
    )
    a(_df_to_md(perf))
    a("\n**Risk score bands** (observed default rate should rise monotonically):\n")
    a(_df_to_md(pd_res.score_bands))
    a("\n![PD ROC](figures/pd_roc.png)")
    a("![PD Calibration](figures/pd_calibration.png)")
    a("![PD Score Bands](figures/pd_score_bands.png)\n")

    # --- Model 2: LGD ---
    a("## 2. Loss Given Default (LGD)\n")
    lm = lgd_res.metrics
    a(f"- Defaulted loans used: **{lm['n_defaulted']:,}**")
    a(f"- MAE: **{lm['mae']:.4f}**, RMSE: **{lm['rmse']:.4f}**, R²: **{lm['r2']:.3f}**")
    a(f"- Mean actual LGD: **{fmt_pct(lm['mean_actual_lgd'])}** vs "
      f"predicted **{fmt_pct(lm['mean_predicted_lgd'])}**\n")
    a("**Segment-level error (by sector):**\n")
    a(_df_to_md(lgd_res.segment_errors))
    a("\n**Top LGD drivers (permutation importance):**\n")
    a(_df_to_md(lgd_res.importance.head(6)))
    a("\n![LGD Scatter](figures/lgd_scatter.png)")
    a("![LGD Importance](figures/lgd_importance.png)\n")

    # --- Model 3: ECL ---
    a("## 3. Expected Credit Loss (ECL) engine\n")
    a("ECL = PD × LGD × EAD × discount factor, computed per IFRS 9 stage and "
      "probability-weighted across macro scenarios.\n")
    a("**ECL by stage:**\n")
    a(_df_to_md(ecl_res.by_stage))
    a("\n**ECL by scenario (probability-weighted):**\n")
    a(_df_to_md(ecl_res.by_scenario))
    a("\n![ECL by Stage](figures/ecl_by_stage.png)")
    a("![ECL by Scenario](figures/ecl_by_scenario.png)\n")

    # --- Model 4: Stress ---
    a("## 4. Portfolio stress testing\n")
    a("**Scenario expected loss:**\n")
    a(_df_to_md(stress_res.scenario_summary))
    a("\n**Single-factor sensitivity:**\n")
    a(_df_to_md(stress_res.sensitivity))
    cm = stress_res.concentration_metrics
    a(f"\n**Concentration:** sector HHI **{cm['sector_hhi']:.3f}**, "
      f"region HHI **{cm['region_hhi']:.3f}**. "
      f"Largest sector: **{cm['top_sector']}** "
      f"({fmt_pct(cm['top_sector_share'])} of exposure); "
      f"largest region: **{cm['top_region']}** "
      f"({fmt_pct(cm['top_region_share'])}).\n")
    a("![Stress Scenarios](figures/stress_scenarios.png)")
    a("![Sector Concentration](figures/stress_sector_concentration.png)")
    a("![Region Concentration](figures/stress_region_concentration.png)\n")

    # --- Model 5: EWS ---
    a("## 5. Early-warning / delinquency model\n")
    em = ews_res.metrics
    a(f"- ROC-AUC: **{em['roc_auc']:.3f}**, PR-AUC: **{em['pr_auc']:.3f}**")
    a(f"- Event (delinquency) rate: **{fmt_pct(em['event_rate'])}**")
    a(f"- Top-decile capture rate: **{fmt_pct(em['top_decile_capture_rate'])}** "
      "of all delinquency events fall in the highest-risk 10% of the book\n")
    a("**Top 10 watchlist accounts:**\n")
    watch_cols = ["loan_id", "sector", "region", "ews_score",
                  "expected_loss_at_risk", "current_dpd", "missed_payments_12m"]
    a(_df_to_md(ews_res.watchlist[watch_cols].head(10)))
    a("\n![Watchlist](figures/ews_watchlist.png)\n")

    a("---\n")
    a("*Generated by `run_pipeline.py`. See `docs/model_cards.md` for assumptions "
      "and limitations of each model.*")

    out = REPORTS_DIR / "model_summary.md"
    out.write_text("\n".join(lines))
    return out
